// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADv6ef4O-MYnsJGufp7aaigIK-XWCiSkg',
    appId: '1:92147041494:web:97bc30ad19c397c2063577',
    messagingSenderId: '92147041494',
    projectId: 'shop-smp',
    authDomain: 'shop-smp.firebaseapp.com',
    storageBucket: 'shop-smp.appspot.com',
    measurementId: 'G-8YMX2RJ61J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmOD2PbNZw5ZSAAEwULE4g7lEaSyJ4RY8',
    appId: '1:92147041494:android:eec06d2aac9ab7c6063577',
    messagingSenderId: '92147041494',
    projectId: 'shop-smp',
    storageBucket: 'shop-smp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOpYmxhT5lYDbs6PER4Rw',
    appId: '1:92147041494:ios:f203e9b80cf3f0b8063577',
    messagingSenderId: '92147041494',
    iosBundleId: 'com.example.smp',
    storageBucket: 'shop-smp.appspot.com',
    projectId: 'shop-smp',
  );

}